featured: true

title:
  fa: "داشبورد مدیریت T-Board"
  en: "T-Board Admin Dashboard"

description:
  fa: "یک داشبورد مدیریت مدرن، واکنش‌گرا و چندزبانه."
  en: "A modern, responsive and multilingual admin dashboard."

preview: "https://tboard.faridteymouri.com"

banner: "/t-board-banner.png"

skills:
  - name: "Next.js"
    icon:
      light: "skill-icons:nextjs-light"
      dark: "skill-icons:nextjs-dark"

  - name: "TypeScript"
    icon:
      light: "skill-icons:typescript"
      dark: "skill-icons:typescript"

  - name: "Tailwind CSS"
    icon:
      light: "skill-icons:tailwindcss-light"
      dark: "skill-icons:tailwindcss-dark"

  - name: "TanStack Query"
    icon:
      light: "simple-icons:tanstack"
      dark: "simple-icons:tanstack"

  - name: "shadcn/ui"
    icon:
      light: "vscode-icons:file-type-light-shadcn"
      dark: "vscode-icons:file-type-shadcn"

  - name: "Docker"
    icon:
      light: "skill-icons:docker"
      dark: "skill-icons:docker"
