import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import { notFound } from "next/navigation";
import { ThemeProvider } from "@/components/providers/theme-provider";
import "../globals.css";
import { ThemePresetProvider } from "@/components/layout/theme-customizer/theme-preset-provider";
import { cn } from "@/lib/utils";
import { hasLocale } from "@/i18n/config";
import { cookies } from "next/headers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const shabnam = localFont({
  src: [
    {
      path: "../../fonts/Shabnam.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../fonts/Shabnam-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../fonts/Shabnam-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-shabnam",
});

type RootLayoutProps = {
  children: React.ReactNode;
  params: Promise<{
    locale: string;
  }>;
};
export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const cookieStore = await cookies();
  const storedPreset = cookieStore.get("theme-preset")?.value;

  const validPresets = [
    "default",
    "amber-minimal",
    "amethyst-haze",
    "bold-tech",
    "bubblegum",
    "caffeine",
  ] as const;

  const themePreset = validPresets.includes(
    storedPreset as (typeof validPresets)[number],
  )
    ? storedPreset
    : "default";
  const { locale } = await params;

  if (!hasLocale(locale)) {
    notFound();
  }

  return (
    <html
      lang={locale}
      dir={locale === "fa" ? "rtl" : "ltr"}
      suppressHydrationWarning
      data-theme={themePreset}
      className={cn(
        shabnam.className,
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ThemePresetProvider />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
