import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import { notFound } from "next/navigation";
import { cookies } from "next/headers";

import { QueryProvider } from "@/components/providers/query-provider";
import { ThemeProvider } from "next-themes";
import { cn } from "@/lib/utils";
import { hasLocale } from "@/i18n/config";

import "../globals.css";

const shabnam = localFont({
  src: [
    {
      path: "../../fonts/Shabnam.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../fonts/Shabnam-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../fonts/Shabnam-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-shabnam",
});

const geist = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const validPresets = [
  "default",
  "amber-minimal",
  "rose-pine",
  "bold-tech",
  "bubblegum",
  "caffeine",
] as const;

const validWidths = ["container", "fluid"] as const;

const validOrientations = ["vertical", "horizontal"] as const;

type RootLayoutProps = {
  children: React.ReactNode;
  params: Promise<{
    locale: string;
  }>;
};

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { locale } = await params;

  if (!hasLocale(locale)) {
    notFound();
  }

  const cookieStore = await cookies();

  const storedPreset = cookieStore.get("theme-preset")?.value;
  const storedWidth = cookieStore.get("theme-width")?.value;
  const storedOrientation = cookieStore.get("theme-menu-orientation")?.value;

  const themePreset = validPresets.includes(
    storedPreset as (typeof validPresets)[number],
  )
    ? storedPreset
    : "default";

  const themeWidth = validWidths.includes(
    storedWidth as (typeof validWidths)[number],
  )
    ? storedWidth
    : "container";

  const themeOrientation = validOrientations.includes(
    storedOrientation as (typeof validOrientations)[number],
  )
    ? storedOrientation
    : "vertical";

  const fontClassName = locale === "fa" ? shabnam.className : geist.className;

  return (
    <html
      lang={locale}
      dir={locale === "fa" ? "rtl" : "ltr"}
      suppressHydrationWarning
      data-theme={themePreset}
      data-theme-width={themeWidth}
      data-menu-orientation={themeOrientation}
      className={cn(
        fontClassName,
        geist.variable,
        geistMono.variable,
        "h-full",
        "antialiased",
      )}
    >
      <body className="flex min-h-full flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>{children}</QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
